"""user role to check constraint

Revision ID: 0ae6ee00b92b
Revises: 6aa8c7b2378b
Create Date: 2026-08-21 21:53:06.470365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ae6ee00b92b'
down_revision: Union[str, Sequence[str], None] = '6aa8c7b2378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'NONE', name='userrole'),
               type_=sa.Enum('ADMIN', 'USER', 'NONE', name='userrole', native_enum=False, create_constraint=True, length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'NONE'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', 'NONE', name='userrole', native_enum=False, create_constraint=True, length=16),
               type_=postgresql.ENUM('ADMIN', 'USER', 'NONE', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'NONE'::userrole"))
    # ### end Alembic commands ###
