"""changed created_at to added_at; added naming convention;

Revision ID: 186f3cf7cedf
Revises: cb531368dc55
Create Date: 2026-07-31 09:40:58.980239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186f3cf7cedf'
down_revision: Union[str, Sequence[str], None] = 'cb531368dc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(op.f('uq_channels_channel_id'), 'channels', ['channel_id'])
    op.drop_column('channels', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_channels_channel_id'), 'channels', type_='unique')
    op.drop_column('channels', 'added_at')
    # ### end Alembic commands ###
