"""added scheduled_at, ix_post_due and publishing status for posts

Revision ID: 6aa8c7b2378b
Revises: faa7be71eab1
Create Date: 2026-08-21 18:02:45.150490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa8c7b2378b'
down_revision: Union[str, Sequence[str], None] = 'faa7be71eab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_posts_due', 'posts', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.drop_constraint("ck_posts_poststatus", "posts", type_="check")
    op.create_check_constraint(
        "ck_posts_poststatus", "posts",
        "status IN ('DRAFT', 'SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_posts_poststatus", "posts", type_="check")
    op.create_check_constraint(
        "ck_posts_poststatus", "posts",
        "status IN ('DRAFT', 'PUBLISHED', 'FAILED')",
    )
    op.drop_index('ix_posts_due', table_name='posts', postgresql_where=sa.text("status = 'SCHEDULED'"))
    op.drop_column('posts', 'scheduled_at')
    # ### end Alembic commands ###
