"""added index for unused quiz topics;

Revision ID: 9679959b3bba
Revises: dee8ae830cb6
Create Date: 2026-08-02 18:27:40.756149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9679959b3bba'
down_revision: Union[str, Sequence[str], None] = 'dee8ae830cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_quiz_topics_unused', 'quiz_topics', ['channel_id'], unique=False, postgresql_where=sa.text('used_in_post IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_topics_unused', table_name='quiz_topics', postgresql_where=sa.text('used_in_post IS NULL'))
    # ### end Alembic commands ###
