"""replace existing_posts with cahnnels and quiz_topics

Revision ID: cb531368dc55
Revises: 8e346692806e
Create Date: 2026-07-31 09:28:45.731725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb531368dc55'
down_revision: Union[str, Sequence[str], None] = '8e346692806e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=63), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=True)
    op.create_table('quiz_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_in_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'topic', name='uq_channel_topic')
    )
    op.create_index(op.f('ix_quiz_topics_channel_id'), 'quiz_topics', ['channel_id'], unique=False)
    op.drop_table('existingposts')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.create_table('existingposts',
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'post_id', name=op.f('existingposts_pkey'))
    )
    op.drop_index(op.f('ix_quiz_topics_channel_id'), table_name='quiz_topics')
    op.drop_table('quiz_topics')
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
