"""removed index from channel_id in quiz topic model

Revision ID: dee8ae830cb6
Revises: 186f3cf7cedf
Create Date: 2026-08-02 18:20:26.996346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee8ae830cb6'
down_revision: Union[str, Sequence[str], None] = '186f3cf7cedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_topics_channel_id'), table_name='quiz_topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quiz_topics_channel_id'), 'quiz_topics', ['channel_id'], unique=False)
    # ### end Alembic commands ###
