"""add posts table and link to quiz_topics

Revision ID: faa7be71eab1
Revises: 9679959b3bba
Create Date: 2026-08-20 20:59:41.196155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faa7be71eab1'
down_revision: Union[str, Sequence[str], None] = '9679959b3bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('post_type', sa.Enum('QUIZ', 'MATERIAL', 'SOURCES', name='posttype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'FAILED', name='poststatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], name=op.f('fk_posts_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_foreign_key(op.f('fk_quiz_topics_used_in_post_posts'), 'quiz_topics', 'posts', ['used_in_post'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quiz_topics_used_in_post_posts'), 'quiz_topics', type_='foreignkey')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
